#!/usr/bin/env bash
# Build /llms-full.txt — a single plaintext concatenation of every HTML
# page on the site, with page boundaries marked by an H1-style header.
# This is the "give me the whole site as one document" feed for LLMs
# that prefer corpus reading over targeted crawling.
#
# Output: llms-full.txt at the repo root.
#
# Implementation: uses python3 (stdlib only) for HTML→text because
# pandoc isn't on the dev box and a sed pipeline can't reliably handle
# nested tags / entities / <script> stripping. No external Python deps.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${REPO_ROOT}/llms-full.txt"
SITE_URL="https://althor.dev"

cd "${REPO_ROOT}"

# Page order — home first, then sections, then leaves. Mirrors the
# information architecture so a reader who skims top-to-bottom gets
# the intended onboarding flow.
PAGES=(
  "index.html|/"
  "work/index.html|/work/"
  "work/extraction-pipeline/index.html|/work/extraction-pipeline/"
  "work/governance-platform/index.html|/work/governance-platform/"
  "work/spire/index.html|/work/spire/"
  "writing/index.html|/writing/"
  "writing/agent-security-review/index.html|/writing/agent-security-review/"
  "writing/entra-workload-identities/index.html|/writing/entra-workload-identities/"
  "writing/mcp-copilot-studio/index.html|/writing/mcp-copilot-studio/"
  "writing/mcp-server-boundaries/index.html|/writing/mcp-server-boundaries/"
  "checklist/index.html|/checklist/"
)

# Build a temporary file then mv into place so partial writes can't
# leave the published artifact half-rendered.
TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

{
  printf '# Althor Consulting — full site corpus\n'
  printf '> Generated by scripts/build-llms-full.sh on %s\n' "$(date -u +%Y-%m-%d)"
  printf '> Source: %s/llms-full.txt\n\n' "${SITE_URL}"
  printf 'This file concatenates the plain-text content of every page on althor.dev.\n'
  printf 'Each page is delimited by a header of the form "===== /path/ =====".\n'
} > "${TMP}"

for entry in "${PAGES[@]}"; do
  file="${entry%%|*}"
  path="${entry##*|}"
  if [[ ! -f "${file}" ]]; then
    echo "warn: ${file} missing, skipping" >&2
    continue
  fi

  {
    printf '\n\n===== %s =====\n' "${path}"
    printf '%s%s\n\n' "${SITE_URL}" "${path}"
  } >> "${TMP}"

  python3 - "${file}" >> "${TMP}" <<'PYEOF'
import sys, re, html
from html.parser import HTMLParser

class TextExtractor(HTMLParser):
    SKIP = {"script", "style", "noscript", "svg", "head", "nav", "footer"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.skip_depth = 0
        self.chunks = []
        self.in_pre = False

    def handle_starttag(self, tag, attrs):
        if tag in self.SKIP:
            self.skip_depth += 1
            return
        if tag == "pre":
            self.in_pre = True
        if tag in ("p", "li", "h1", "h2", "h3", "h4", "h5", "h6",
                   "div", "section", "article", "header", "tr",
                   "br", "blockquote", "pre"):
            self.chunks.append("\n")
        if tag in ("h1", "h2", "h3"):
            # add a small lead marker so model can see hierarchy
            level_marker = {"h1": "\n# ", "h2": "\n## ", "h3": "\n### "}[tag]
            self.chunks.append(level_marker)

    def handle_endtag(self, tag):
        if tag in self.SKIP:
            self.skip_depth = max(0, self.skip_depth - 1)
            return
        if tag == "pre":
            self.in_pre = False
        if tag in ("p", "li", "h1", "h2", "h3", "h4", "h5", "h6",
                   "div", "section", "article", "blockquote", "pre"):
            self.chunks.append("\n")

    def handle_data(self, data):
        if self.skip_depth:
            return
        if self.in_pre:
            self.chunks.append(data)
        else:
            # collapse internal whitespace; preserve word boundaries
            text = re.sub(r"\s+", " ", data)
            if text.strip():
                self.chunks.append(text)

    def text(self):
        raw = "".join(self.chunks)
        # collapse runs of >2 blank lines and trim trailing ws on each line
        raw = re.sub(r"[ \t]+\n", "\n", raw)
        raw = re.sub(r"\n{3,}", "\n\n", raw)
        return raw.strip() + "\n"

path = sys.argv[1]
with open(path, "r", encoding="utf-8") as fh:
    src = fh.read()

ex = TextExtractor()
ex.feed(src)
sys.stdout.write(ex.text())
PYEOF
done

mv "${TMP}" "${OUT}"

chars=$(wc -c < "${OUT}")
lines=$(wc -l < "${OUT}")
printf 'wrote %s (%s chars, %s lines)\n' "${OUT}" "${chars}" "${lines}"
